#!/bin/sh
# Show files names bigger than two mebibytes in the current directory or at the path optionally given.
# Doesn't handle file names with newlines in them.

if test "$#" = 1; then
	# Escape cd's flags.
	case "$1" in
	/*)
		cd "$1"
	;;
	*)
		cd "./$1"
	;;
	esac || exit 1
fi

# The minimal size (in megabytes) for a path to be included in the listing.
minimum=2

# Match all files in the directory.
# https://www.etalabs.net/sh_tricks.html, "Using globs to match dotfiles".
GLOB='.[!.]* ..?* *'

IFS='
'

# Only keep existing files to avoid adding globs which failed to match.
# shellcheck disable=SC2046 # Word splitting.
set -- $(
	# The glob itself should be split by spaces.
	IFS=' '
	for path in $GLOB; do
		test -e "$path" && printf '%s\n' "$path"
	done
)

(
	du -sk "$@" | sort -rn | awk '{
		split("K M G T P", exponents)
		significand = $1
		i = 1
		while (significand >= 1024 && i < length(exponents)) {
			significand /= 1024
			i++
		}
		if ($1 >= '$minimum' * 1024) {
			$1 = sprintf("%6.1f%s ", significand, exponents[i])
			print $0
		}
	}'
) 2> /dev/null
